title: malinowski.dev
email: rafal+blog@malinowski.be
description: "Rafał Malinowski dev thoughts"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://malinowski.dev"

permalink: ":title.html"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
sass:
    style: compressed
exclude:
    - node_modules/
    - package.json
    - CNAME
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed